name: CSU Library Reserve

on:
  workflow_dispatch:

  schedule:
    - cron: '56 21 * * *'
    - cron: '57 21 * * *'
    - cron: '58 21 * * *'
    - cron: '59 21 * * *'
    - cron: '00 22 * * *'

jobs:
  reserve:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
        
    - name: Reserve
      run: |
        user='${{ secrets.USER }}'
        pwd='${{ secrets.PWD }}'
        python3 helper.py --action 'reserve' --userid $user --password $pwd
    - name: Commit
      run: |
        git config --global user.name csuboo
        git config --global user.email "mm04315@qq.com"
        git add .
        git commit -m "Update library.log" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
